export const words = [
  "отвага",
  "удар",
  "ореол",
  "скорость",
  "колючка",
  "охрана",
  "похвала",
  "обрыв",
  "попытка",
  "шут",
  "чума",
  "авиация",
  "гусеница",
  "зеркало",
  "резать",
  "рукав",
  "стук",
  "салфетка",
  "демократия",
  "ворон",
  "улитка",
  "мираж",
  "вальс",
  "канарейка",
  "нормальный",
  "ужесточить",
  "гимнастика",
  "воздух",
  "свадебный",
  "сатана",
  "трофей",
  "ванная",
  "дуэль",
  "кроссворд",
  "царапина",
  "портфель",
  "север",
  "команда",
  "росток",
  "шаль",
  "билет",
  "глава",
  "ипподром",
  "чавкать",
  "убийство",
  "ягодицы",
  "возраст",
  "бабочка",
  "центр",
  "исправление",
  "гололед",
  "Джокер",
  "сухой",
  "наглый",
  "трубка",
  "крыша",
  "балласт",
  "журавль",
  "фортепиано",
  "цапля",
  "бровь",
  "вставать",
  "водитель",
  "старец",
  "бензопила",
  "симптом",
];

export const param = [
  { top: '50%', left: '10%', rotate: -5, scale: .9 },
  { top: '52%', left: '20%', rotate: -25, scale: .7 },
  { top: '55%', left: '30%', rotate: -45, scale: .6 },
  { top: '65%', left: '10%', rotate: -40, scale: .7 },
  { top: '65%', left: '20%', rotate: -15, scale: .6 },
  { top: '77%', left: '20%', rotate: 20, scale: .6 },
  { top: '83%', left: '8%', rotate: -15, scale: .9 },
  { top: '68%', left: '28%', rotate: 5, scale: .6 },
  { top: '90%', left: '15%', rotate: -45, scale: .7 },
  { top: '88%', left: '25%', rotate: -25, scale: .6 },
  { top: '90%', left: '33%', rotate: -45, scale: .8 },
  { top: '75%', left: '35%', rotate: -15, scale: .6 },
  { top: '75%', left: '42%', rotate: -70, scale: .6 },
  { top: '94%', left: '40%', rotate: -35, scale: .7 },
  { top: '75%', left: '50%', rotate: 45, scale: .8 },
  { top: '90%', left: '50%', rotate: 25, scale: .5 },
  { top: '70%', left: '57%', rotate: 5, scale: .6 },
  { top: '85%', left: '57%', rotate: -45, scale: .6 },
  { top: '95%', left: '60%', rotate: -35, scale: .4 },
  { top: '75%', left: '65%', rotate: -45, scale: .4 },
  { top: '88%', left: '65%', rotate: 45, scale: .6 },
  { top: '92%', left: '73%', rotate: 80, scale: .9 },
  { top: '70%', left: '70%', rotate: 45, scale: .8 },
  { top: '95%', left: '80%', rotate: 45, scale: .6 },
  { top: '80%', left: '80%', rotate: -45, scale: .7 },
  { top: '93%', left: '90%', rotate: 0, scale: .6 },
  { top: '80%', left: '95%', rotate: 0, scale: .5 },
  { top: '80%', left: '86%', rotate: -50, scale: .5 },
  { top: '65%', left: '86%', rotate: 25, scale: .7 },
  { top: '65%', left: '77%', rotate: 35, scale: .7 },
  { top: '65%', left: '95%', rotate: 75, scale: .6 },
  { top: '55%', left: '70%', rotate: 15, scale: .6 },
  { top: '55%', left: '80%', rotate: 0, scale: .6 },
  { top: '52%', left: '90%', rotate: 15, scale: .9 },
  { top: '43%', left: '30%', rotate: -5, scale: .6 },
  { top: '35%', left: '10%', rotate: -40, scale: .7 },
  { top: '35%', left: '20%', rotate: -15, scale: .6 },
  { top: '23%', left: '20%', rotate: 20, scale: .6 },
  { top: '17%', left: '8%', rotate: -15, scale: .7 },
  { top: '32%', left: '28%', rotate: 5, scale: .6 },
  { top: '10%', left: '17%', rotate: -45, scale: .7 },
  { top: '12%', left: '25%', rotate: -25, scale: .6 },
  { top: '10%', left: '33%', rotate: 45, scale: .8 },
  { top: '25%', left: '35%', rotate: -15, scale: .6 },
  { top: '25%', left: '42%', rotate: -70, scale: .6 },
  { top: '6%', left: '43%', rotate: -55, scale: .7 },
  { top: '25%', left: '50%', rotate: 45, scale: .8 },
  { top: '10%', left: '50%', rotate: 25, scale: .5 },
  { top: '30%', left: '60%', rotate: 5, scale: .6 },
  { top: '15%', left: '57%', rotate: -45, scale: .6 },
  { top: '5%', left: '60%', rotate: -35, scale: .4 },
  { top: '21%', left: '62%', rotate: 15, scale: .5 },
  { top: '12%', left: '65%', rotate: 45, scale: .6 },
  { top: '12%', left: '72%', rotate: 80, scale: .7 },
  { top: '30%', left: '70%', rotate: -45, scale: .8 },
  { top: '5%', left: '80%', rotate: 45, scale: .6 },
  { top: '20%', left: '80%', rotate: -45, scale: .7 },
  { top: '10%', left: '90%', rotate: -10, scale: .6 },
  { top: '20%', left: '95%', rotate: 0, scale: .5 },
  { top: '22%', left: '88%', rotate: -45, scale: .7 },
  { top: '35%', left: '86%', rotate: 5, scale: .7 },
  { top: '35%', left: '77%', rotate: 35, scale: .7 },
  { top: '35%', left: '95%', rotate: 75, scale: .6 },
  { top: '45%', left: '70%', rotate: -15, scale: .5 },
  { top: '45%', left: '80%', rotate: -20, scale: .6 },
  { top: '43%', left: '90%', rotate: 15, scale: .5 },
];
